const dotenv = require("dotenv");
dotenv.config({ path: ".env" });
const myDateModule = require("./util/date");
const express = require("express");
const app = express();
const morgan = require("morgan");
const cors = require("cors");
const bodyParser = require("body-parser");
const userRouter = require("./routes/user");
const adminRouter = require("./routes/admin");
// const postRouter = require("./routes/post");
const posttestRouter = require("./routes/posttest");
const notiRouter = require("./routes/notification");
// const roleRouter = require("./routes/role");
const bandRouter = require("./routes/band");
const followRouter = require("./routes/follow");
const reportRouter = require("./routes/report");
const commentpostRouter = require("./routes/commentpost");
const commentvideoRouter = require("./routes/commentvideo");
const videoRouter = require("./routes/video");
const otpRouter = require("./routes/otp");
app.use(cors());
app.use(morgan("dev"));
app.use("/uploads", express.static("uploads"));
app.use("/uploads/images/bands", express.static("uploads/images/bands"));
app.use("/uploads/images/users", express.static("uploads/images/users"));
app.use("/uploads/videos/users", express.static("uploads/videos/users"));
app.use("/uploads/videos/bands", express.static("uploads/videos/bands"));
// app.use("/uploads", express.static("uploads/images/users"));
app.use(express.json());
app.use(bodyParser.urlencoded({ extended: true }));
// !middleware passing Json => Obj
console.log(myDateModule.getCurrentDateTimeFormatted());
app.use("/api/users", userRouter);
app.use("/api/admins", adminRouter);
// app.use("/api/posts", postRouter);
// app.use("/api/roles", roleRouter);
// app.use("/api/comments", commentRouter);
app.use("/api/bands", bandRouter);
app.use("/api/reports", reportRouter);
app.use("/api/notifications", notiRouter);
app.use("/api/follows", followRouter);
app.use("/api/poststest", posttestRouter);
app.use("/api/videos", videoRouter);
app.use("/api/commentsposts", commentpostRouter);
app.use("/api/commentvideos", commentvideoRouter);
app.use("/api/otp", otpRouter);
// app.use("/api/posts")ฏ
// const userRouter = require("./user");
// app.use("/users", userRouter);
app.listen(process.env.APP_PORT, () => {
  console.log(`server is running on port ${process.env.APP_PORT}`);
});
